 const order = {
      "amount" : 3400,
      "bill_notes" : "Thank you for Shopping with us",
      "cancelled" : false,
      "cart_id" : 1458321,
      "checkout_fields" : [
         {
            "name" : "Upload Picture",
            "slug" : "upload-picture",
            "type" : "IMAGE",
            "value" : null
         },
         {
            "name" : "Prescription",
            "slug" : "prescription-1",
            "type" : "IMAGE",
            "value" : null
         }
      ],
      "coupon_code" : "CODE35",
      "coupon_discount" : 120.9,
      "coupon_id" : 15341,
      "created_at" : "2023-02-18T08:11:56.000+0000",
      "customer_id" : 629026,
      "deleted" : false,
      "delivered_on" : "2023-02-18T08:14:00.000+0000",
      "delivery_mode" : "PICKUP",
      "discount" : 0,
      "display_id" : "ORD-0728",
      "due_amount" : 34,
      "earn_points" : 54,
      "estimate" : false,
      "final_discount" : 120.9,
      "final_sale_price" : 1088.1,
      "fixed_discount" : 0,
      "guest_checkout" : false,
      "id" : 835759,
      "intra_state" : false,
      "invoice" : false,
      "invoice_date" : "2023-02-18T08:11:56.000+0000",
      "invoice_id" : "DI20233670",
      "invoice_location" : "https://storage.googleapis.com/shy-in/9/2/DI20233670.pdf",
      "last_payment_date" : "2023-02-18T00:00:00.000+0000",
      "mrp" : 1269,
      "notes" : "sample text",
      "online_order" : true,
      "order_address" : {
         "city" : "Kolkata",
         "country" : null,
         "created_at" : "2023-02-18T08:24:11.000+0000",
         "customer_id" : 629026,
         "customer_name" : "Sudipta",
         "id" : 430794,
         "lat" : null,
         "lng" : null,
         "mobile" : "7278591612",
         "pincode" : "700001",
         "state" : "West Bengal",
         "street1" : "Kolkata ",
         "street2" : "",
         "updated_at" : "2023-02-18T08:24:11.000+0000"
      },
      "order_discount" : 0,
      "order_items" : [
         {
            "cess" : 0,
            "cgst" : 0,
            "created_at" : "2023-02-18T08:11:56.000+0000",
            "display_name" : "Happilo Premium Pumpkin Seeds - 200gm",
            "extra_fields" : [
               {
                  "ef_id" : 593274,
                  "name" : "Weight ",
                  "slug" : "weight",
                  "type" : "TEXT",
                  "val" : "200gm"
               }
            ],
            "fixed_discount" : 0,
            "id" : 1915869,
            "igst" : 0,
            "image" : "https://storage.googleapis.com/shy-pub/275981/1670068159995_SKU-0050_0.jpg",
            "measuring_unit" : "pcs",
            "mrp" : 195,
            "name" : "Happilo Premium Pumpkin Seeds - 200gm",
            "org_id" : 9,
            "pp_tax_included" : false,
            "purchase_price" : 0,
            "qty" : 3,
            "quantity" : 3,
            "sale_price" : 175,
            "sgst" : 0,
            "sku" : "SKU-3889",
            "sp_tax_included" : true,
            "store_id" : 2,
            "subscribed" : false,
            "tax" : 0,
            "total_tax_in_per" : 0,
            "updated_at" : "2023-02-18T08:24:13.000+0000",
            "utgst" : 0,
            "valid_mrp" : 195
         },
         {
            "cess" : 0,
            "cgst" : 0,
            "created_at" : "2023-02-18T08:11:56.000+0000",
            "display_name" : "Cadbury Bourn Vita - 500gm",
            "extra_fields" : [
               {
                  "ef_id" : 577475,
                  "name" : "Size",
                  "slug" : "size",
                  "type" : "TEXT",
                  "val" : "500gm"
               }
            ],
            "fixed_discount" : 0,
            "id" : 1915870,
            "igst" : 0,
            "image" : "https://storage.googleapis.com/shy-pub/275981/1669980691012_SKU-0033_0.jpg",
            "mrp" : 228,
            "name" : "Cadbury Bourn Vita - 500gm",
            "org_id" : 9,
            "pp_tax_included" : false,
            "purchase_price" : 0,
            "qty" : 3,
            "quantity" : 3,
            "sale_price" : 228,
            "sgst" : 0,
            "sku" : "SKU-3872",
            "sp_tax_included" : true,
            "store_id" : 2,
            "subscribed" : false,
            "tax" : 0,
            "total_tax_in_per" : 0,
            "updated_at" : "2023-02-18T08:11:56.000+0000",
            "utgst" : 0,
            "valid_mrp" : 228
         }
      ],
      "org_customer_id" : 497935,
      "org_customer_mobile" : "7278591612",
      "org_customer_name" : "Sudipta gupta",
      "org_customer_type" : "CONSUMER",
      "org_id" : 9,
      "org_name" : "The Mobile Corner",
      "org_store_customer_id" : 501521,
      "packaging_charge" : 0,
      "payment_mode" : "COD",
      "payment_type" : "CASH",
      "purchase_order" : false,
      "redeem_points" : 80,
      "returned" : false,
      "round_value" : 0,
      "sale_price" : 1209,
      "sale_price_after_discocunt" : 1088.1,
      "sales_with_other_charges" : 1209,
      "savings" : 120,
      "shipping_charge" : 0,
      "state" : "COMPLETE",
      "status" : "DELIVERED",
      "store_id" : 2,
      "store_name" : "Pizza What",
      "sub_total" : 230,
      "tax_amount" : 120,
      "term" : "PAID",
      "tos" : "",
      // "some text representing terms & conditions ",
      "type" : "ONLINE",
      "updated_at" : "2023-04-18T06:34:11.919+0000",
      "user_id" : 0,
      "version" : "V3",
      "weight" : 0
   };

  const store = {
      "ac_holder_name" : "Indar Kriplani",
      "ac_type" : "SAVINGS",
      "account_number" : "000201656113",
      "activate_at" : null,
      "attributes" : null,
      "bank_details" : null,
      "bank_name" : "ICICI Bank",
      "business_category" : "general-store",
      "business_name" : "Shrimati Sarees Limited",
      "business_type" : "PARTNERSHIP",
      "cin" : null,
      "city" : "Bengaluru",
      "created_at" : "2019-12-19T11:30:56.000+0000",
      "domain" : "store.shoopy.in",
      "email" : "indar.kriplani@gmail.com",
      "favicon" : null,
      "fssai_no" : "",
      "gstin" : "233203203A23235",
      "has_ssl" : true,
      "id" : 2,
      "ifsc_code" : "ICIC0000002",
      "invoice_template" : "THERMAL_INVOICE_BLACK",
      "large_image" : "https://aftwhtbtmp.cloudimg.io/v7/aftwhtbtmp.cloudimg.io/v7/storage.googleapis.com/shy-pub/_static/cat-imgs/veg3.jpg",
      "lat" : 13.0603,
      "lng" : 77.6361,
      "locality" : "Narayanapuraa",
      "logo" : "https://storage.googleapis.com/shy-pub/9/1672332610702_IMG20221212121707.jpeg",
      "name" : "Shrimati Stores",
      "org_id" : 9,
      "org_name" : "The Mobile Corner",
      "other_category" : null,
      "pages" : null,
      "pan" : null,
      "partner_slug" : "",
      "payment_mode" : "COD",
      "phone" : "9910100819",
      "pincode" : "560077",
      "plan" : "BUSINESS",
      "previous_domain" : null,
      "seo_setting" : null,
      "signature_url" : "https://storage.googleapis.com/shy-pub/9/1675351708612_1654846276341signature.jpeg",
      "slug" : "shrimati",
      "state" : "Karnataka",
      "status" : "ACTIVE",
      "status_reason" : null,
      "store_setting" : {
         "address_mode" : "FORM_MAP",
         "alternate_number" : null,
         "auto_verify" : false,
         "banner_url" : null,
         "card_type" : "TWO_CARD",
         "cart_note" : "<p><strong>Cart Note</strong>Only delivered between 10-5</p>",
         "closes_at" : "8 PM",
         "created_at" : "2020-07-31T09:41:22.000+0000",
         "delivery_ends_at" : null,
         "delivery_fee" : 0,
         "delivery_in_hrs" : 0,
         "delivery_mode" : "DELIVERY_PICKUP",
         "delivery_radius" : 3000,
         "delivery_starts_at" : null,
         "disable_pwa" : false,
         "font_family" : "Proxima Nova",
         "force_cod" : null,
         "free_shipping_above" : 500,
         "has_zones" : false,
         "id" : 248,
         "list_view" : false,
         "min_order" : 0,
         "notice" : "Test@test.com",
         "online_confirmed" : false,
         "online_payment_limit" : null,
         "opens_at" : "1 PM",
         "payment_mode" : "COD_ONLINE",
         "punch_line" : "Creative Fashion Vista",
         "return_accepted" : false,
         "select_location" : false,
         "select_pincode" : false,
         "show_negative_stock" : false,
         "show_price_wo_tax" : true,
         "show_sold_out" : true,
         "show_support_mobile" : true,
         "store_id" : 2,
         "support_mobile" : "99999111100",
         "theme" : "basic",
         "theme_color" : "#F6740C",
         "updated_at" : "2023-02-18T08:33:57.000+0000",
         "weekly_off" : null
      },
      "street" : "26/2, Narayanapuraa",
      "street2" : "Narayanapuraa",
      "tc_acknowledged" : false,
      "thumbnail" : null,
      "updated_at" : "2023-02-14T11:05:08.000+0000",
      "upi_address" : "8009551506@oksbi",
      "verified" : null,
      "web_store_disabled" : false
   };

module.exports = {order,store};